qarysite/qary_app/urls.py
# from django.contrib import admin
# from django.urls import path
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns


from qary_app import views


app_name = 'qary_app'


urlpatterns = [


    url(r'answer/', views.reply, name='answer'),
    url(r'^(?P<pk>[-\w]+)/$', views.home_view, name='question'),
    # Rest_framework
    url('basic/', views.API_objects.as_view()),
    url('basic/<int:pk>/', views.API_objects_details.as_view()),




]
urlpatterns = format_suffix_patterns(urlpatterns)

qarysite/qary_post/urls.py
from django.conf.urls import url
from qary_post import views

app_name = 'qary_post'


urlpatterns = [

    url(r'^$', views.PostListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^new/$', views.PostCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.PostUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='delete'),
]

qarysite/qarysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from qary_app import views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home_view),
    url(r'question/', views.home_view, name='question'),
    url(r'answer/', views.reply, name='answer'),
    url(r'^team/$', views.team, name='team'),
    url(r'^nlpia/$', views.nlpia, name='nlpia'),
    url(r'^post/', include('qary_post.urls')),
    url('register/', user_views.register, name='register'),
    url('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url('profile/', user_views.profile, name='profile'),
    url('basic/<int:pk>/', views.API_objects_details.as_view(), name='basic')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


#

qarysite/templates/answer.html
{% extends 'home.html'%}
{% block body_block%}

<div class='jumbotron'>
<h3><h2>Your question: </h2>{{Question}}</h3>
<h3><h2>Bot answer: </h2>{{insert}}</h3>
<p><a href="{% url 'question'%}">Ask another question</a></p>
</div>

{% endblock %}

qarysite/templates/bot.html
{% extends 'home.html'%}
{% block body_block%}



<!--  Question the bot-->            
        <div >
            <div class="list-group-item">
                
              
                <form action = "{% url 'answer'%}" method = "POST"> {% csrf_token %}

<!--                  radio button    -->
                
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="parul_bot" id="parul_bot" autocomplete="off" value="parul_bot" > parul_bot

                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="basebot" id="basebot" autocomplete="off" value="basebot"> basebot
                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="glossary_bot" id="glossary_bot" autocomplete="off" value="glossary_bot" > glossary_bot
                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="pattern_bot" id="pattern_bot" autocomplete="off" value="pattern_bot" > pattern_bot
                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="search_fuzzy_bot" id="search_fuzzy_bot" autocomplete="off" value="search_fuzzy_bot" > search_fuzzy_bot
                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="eliza_bot" id="eliza_bot" autocomplete="off" value="eliza_bot" > eliza_bot
                  </label>
                  <label class="btn btn-outline-secondary">
                    <input type="radio" name="qa_bot" id="qa_bot" autocomplete="off" value="qa_bot" > qa_bot
                  </label>
                  
                </div>
                <p>
                  <ul>
                    <li>parul_bot: Movies bot </li>
                    <li>basebot: </li>
                    <li>glossary: definitions from glossary yml files in data/faq/glossary-*.yml</li>
                    <li>pattern: regex patterns and greeting templates</li>
                    <li>search_fuzzy_bot:</li>
                    <li>eliza: a python port of the ELIZA therapist bot</li>
                    <li>qa_bot: BERT and ALBERT Wikipedia Question Answering (WikiQA reading comprehension tests)</li>
                  </ul>
                </p>
                <br>
                <br>


         

<!-- -------------------------- -->
                <form method="POST">
                <h5 class='dialogue' ><strong class="d-inline-block mb-2 text-success">YOU: <input class= 'dialogue' placeholder="write your question" type="text" name="question_req" size="50">&#128515;</strong></h5>
                
                </form>
              
                <h5 class='dialogue'><strong >BOT: {{insert}}</strong></h5>
                <h5 class='dialogue'><strong class="d-inline-block mb-2 text-success">YOU: {{Question}}</strong></h5>
                
            </div>
<!--  speperate line -->            
              <hr style="font-weight: 700; text-align: center; margin-bottom: 70px; margin-top: 70px; background-color: rgb(40, 167, 69); text-decoration-style: dotted;"></h4>


<!--           Chat history-->            
        <table class="table table-striped">
                <caption>List of Bot Q&A history</caption>
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Your question</th>
                    <th scope="col">Bot answer</th>
                    <th scope="col">Created date</th>
                  </tr>
                </thead>
                <tbody>
                  {%for i in c%}
                  <tr>
                    <td class='dialogue'><strong class="d-inline-block mb-2 text-success">{{i.question}}?</strong></td>
                    <td class='dialogue'>{{i.answer}} </td> 
                    <td>{{i.create_date}}</td>
                  </tr>
                  {%endfor%}

                  </tr>
                </tbody>
        </table>

  <table class="table table-striped">
                <caption>List of Bot Q&A document</caption>
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Summary</th>
                  </tr>
                </thead>
                <tbody>
                  {%for d in document_obj%}
                  <tr>
                    <td><strong class="d-inline-block mb-2 text-success">{{d.title}}?</strong></td>
                    <td>{{d.summary}} </td> 
                  </tr>
                  {%endfor%}

                  </tr>
                </tbody>
        </table>

</div>


{% endblock %}

qarysite/templates/home.html
<!DOCTYPE html>
<html>
<head>


     

    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <style>  
            #rightbox{ 
                float:right; 
                background:blue; 
                width:25%; 
                height:280px; 
            }
            .dialogue{
              font-family:"Comic Sans MS", cursive, sans-serif;
            }

    </style>

    <title>Qary</title>


</head>
 <body style="background-color: rgb(255, 255, 255); position: relative; float: none; opacity: 1; text-align: left;">



<!-- navbar -->
<div class="navbar navbar-dark bg-dark">
    <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'qary_post:list'%}">Blog</a>
    <a class="navbar-brand "href="{% url 'question'%}">BOT</a>
     <a class="navbar-brand "href="https://github.com/nlpia/nlpia-bot">Github</a>
     <a class="navbar-brand" href="{% url 'team'%}">Team</a>
      <a class="navbar-brand" href="{% url 'nlpia'%}">NLPIA</a>

      {%if user.is_authenticated%}
      <a class="navbar-brand" href="{% url 'profile'%}">Profile</a>
      <a class="navbar-brand" href="{% url 'logout'%}">Logout</a>
      {%else%}
      <a class="navbar-brand" href="{% url 'login'%}">Login</a>
      <a class="navbar-brand" href="{% url 'register'%}">Register</a>
      {%endif%}
      
      <form class="form-inline my-2 my-lg-0 " action="http://www.google.com/search" method="GET">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" >
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
</div>



<!-- ------------------------------------------ -->




        {% if messages%}
          {% for message in messages%}
              <div class='alert alert-{{message.tags}}'>
                {{message}}
              </div>
          {% endfor %}
        {% endif %}

<div class="container">
  <br>
        

      {% block body_block%}
        {% endblock %}
</div>








 <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- --------------------footer---------------------------- -->


    <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
          <small class="d-block mb-3 text-muted">©Totalgood 2019-2020</small>
        </div>
    
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="https://github.com/nlpia/nlpia-bot">Resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Business</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="{% url 'team'%}">Team</a></li>
          </ul>
        </div>
      </div>
    </footer>

</body>
</html>

qarysite/templates/nlpia.html
{% extends 'home.html'%}
{% block body_block%}


<h1>qary</h1>
<p>
The `qary` package is both a chatbot framework and a working "reference implementation" virtual assistant that actually assists! Most bots manipulate you to make money for their corporate masters. Your bot can help protect you and amplify your intelligence.

The presentations for San Diego Python User Group are at <a href="http://totalgood.org/midata/talks/">http://totalgood.org/midata/talks/</a> and in `docs/`.
</p>

<h1>Skills</h1>
<p>
The `-b glossary` skill enables `qary` to answer basic "what is" questions about data science for healthcare terms and concepts.
</p>
<h1>bot -b QA</h1>
<p>
It can even answer general factual questions like "What is Barak Obama's Birthday?".
But if the answer isn't explicitly stated on Wikipedia somewhere it will make something up:

<ul>
    <li>YOU: When was Barak Obama born?
</li>
     <li>qary: August 4, 1961
</li>
      <li>YOU: Who invented the perceptron?
</li>
       <li>qary: Everett Rogers
</li>
        <li>YOU: -1 #shouldbe Frank Rosenblatt
</li>
         <li>YOU: Who invented the first perceptron neural network?
</li>
          <li>qary: Gustav Kirchhoff
</li>
           <li>YOU: -1 #shouldbe Frank Rosenblatt
</li>
            <li>YOU: Where do babies come from?
</li>
             <li>qary: industrialized countries
</li>
              <li>YOU: #goodone
</li>

</ul>
</p>


<h1>Others</h1>
<p>
The current version of `qary` can imitate the classic therapist bot "Eliza" and carry on a relatively entertaining conversation based on lines it's read from movie scripts.
You can select any or all of these skills with command line args and the configuration file `~/qary.ini` in your user directory.

You can also expand the complicated questions that qary can answer by adding Q/A pairs to yaml text files in  `data/faq`.
We'll use that to train deep learning networks as well as actual answers if the questions are close enough to your wording in that training file.
</p>


<h1>bot -b your_name_here</h1>
<p>
And soon `qary` will be able to detect your mood and carry on more meaningful conversations, to give you encouragement and emotional support.
We'll have something like this online in a couple months:

<ul>
    <li>bot: How are you doing?
</li>
    <li>YOU: not so great
</li>
    <li>bot: I'm really sorry to hear that. What do you think about doing 10 pushups to get your blood flowing?
</li>
    <li>YOU: not so much
</li>
    <li>bot: Would you like to chat about it?
</li>
    <li>YOU: sure
</li>
    <li>bot: So what are you feeling right now? How does your body feel?
</li>

</ul>
</p>

<h1>Install</h1>
<p>
You'll want to install and use the conda package manager within Anaconda3, especially if your development environment is not an open standard operating system like Linux.

<br />
git clone git@gitlab.com:tangibleai/qary
<br />
cd qary
<br />
conda env create -n qaryenv -f environment.yml  # or environment-windoze.yml
<br />
conda activate qaryenv
<br />
pip install --editable .

</p>
<h1>Usage</h1>
<p>
```bash
$ bot --help
<br />
usage: bot [-h] [--version] [--name STR] [-p] [-b STR] [-v] [-vv] [words [words ...]]
<br />

You can run bot just like any other command line app, giving it your statement/query as an argument.

<br />
$ bot what is an allele
bot: A variant form of a given gene, a version of a known mutation at the same place as the original unmodified gene within a chromosome.
<br />

Travis's probabilistic conversation manager is working nicely to chose a reply from the possiblities generated by the bots:
<br />
<ol>
    <li>qa_bots.py`: BERT and ALBERT Wikipedia Question Answering (WikiQA reading comprehension tests)</li>
    <li>pattern_bots.py`: regex patterns and greeting templates</li>
<li>fuzzy_search_bots.py`: movie dialog fuzzy matching</li>
<li>parul_bots.py`: Wikipedia searches using conventional TFIDFs, like a search engine</li>
<li>eliza_bots.py`: A python port of the ELIZA therapist bot</li>
<li>time_bots.py`: A time and productivity tracker that parses your git logs and bash history</li>
<li>elastic_bots.py`: Semantic search with elasticsearch and `nboost` to find better pages for WikiQA</li>

</ol>

Here's how those bots work together:
<br />

$ bot
<br />
(nlpia) hobs@Hobsons-MacBook-Air:~/code/chatbot/qary$ bot
<br />
# 2019-11-21 12:59:05,854 WARNING:nlpia.constants:107:            Starting logger in nlpia.constants...
<br />
# 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64350/64350 [00:00<00:00, 495935.48it/s]
<br />
YOU: Hi
<br />
BOT: hey there. tired of breathing?
<br />
YOU: Hello
<br />
BOT: How do you do. Please state your problem.
<br />
YOU: What is an ELIZA chatbot?
<br />
BOT: joey never told you we went out, did he?
<br />
YOU: ^[[A
<br />
BOT: I am sorry! I dont understand you
<br />
YOU: What is an ELIZA chatbot?
<br />
BOT: Does that question interest you ?
<br />
YOU: What is a chatbot?
<br />
BOT: hello barbie is an internet-connected version of the doll that uses a <br />
chatbot provided by the company toytalk, which previously used the chatbot <br />
for a range of smartphone-based characters for children.
<br />
YOU: Hello
<br />
BOT: hello.
<br />YOU: Hello
<br />
BOT: How do you do. Please state your problem.
<br />
YOU: bye


Check out the config file in `qary.ini` or `$ bot -h` to change the default bot personalities loaded for your own personalized bot.
</p>

<h1>Approach</h1>
<p>
This hybrid chatbot framework allows you to combine 4 approaches to give you state-of-the-art capability to answer questions and carry on a conversation:
<ol>
    <li>search: [chatterbot](https://github.com/gunthercox/ChatterBot), [will](https://github.com/skoczen/will)</li>
  <li>pattern matching and response templates: Alexa, [AIML](https://github.com/keiffster/program-y)</li>
   <li>generative deep learning: [robot-bernie](https://github.com/nlpia/robot-bernie), [movie-bot](https://github.com/totalgood/nlpia/blob/master/src/nlpia/book/examples/ch10_movie_dialog_chatbot.py)</li> 
<li>grounding: [snips](https://github.com/snipsco/snips-nlu)</li>

</ol>
It's all explained in detail at [NLP in Action](https://www.manning.com/books/natural-language-processing-in-action).

Presentations for San Diego Python User Group are in [docs/](/docs/2019-08-22--San Diego Python User Group -- How to Build a Chatbot.odp) and on the web at [http://totalgood.org/midata/talks](http://totalgood.org/midata/talks/)
</p>

<h1>Contributors (alphabetically)</h1>
<p>
DM @hobson if youwould like to participate in the weekly Zoom collaborative-programming sessions.

- Erturgrul: Turkish wikipedia QA bot (parul bot)
- Hobson (@hobson): infrastructure (CI, webapp) and framework features (nltk->spacy, USE vectors)
- Kendra (@kchalk): semantic search
- Maria Dyshell (tangibleai.com): student and career coaching
- Mohammed Dala (@dala85): django web application
- Nima (@hulkgeek): question answering bot based on his state of the art question classifier
- Olesya: `ElasticSearch` and `nboost`
- Prarit (@praritlamba): BERT
- Travis (@travis-harper): markhov chain reply selection and other data science enhancements
- Xavier (@spirovanni): employment counselor for workforce.org and the city of San Diego
- **YOU:** What AI idea would you like to make a reality?
</p>

<h1>Crazy Ideas</h1>
<p>
Please submit your feature ideas [GitLab issues](https://gitlab.com/tangibleai/qary/issues/). Here are a few ideas to get you started.

1. movie dialog in django database to hold the statement->response pairs
    1. graph schema compatible with MxGraph (draw.io) and other js libraries for editing graphs/flow   charts.
    2. ubuntu dialog corpus in db
    3. mindfulness faq corpus in db
    4. famous quotes as responses to the statement "tell me something inspiring"
    5. jokes for "tell me a joke"
    6. data science faq
    7. nlpia faq
    8. psychology/self-help faq
2. html django template so there is a web interface to the app rather than just the command line command `bot`
3. use Django Rest Framework to create a basic API that returns json containing a reply to any request sent to the local host url, like `http://localhost:8000/api?statement='Hello world'` might return {'reply': 'Hello human!'}
4. have the command line app use the REST API from #3 rather than the slow reloading of the csv file every time you talk to the bot
5. use database full text search to find appropriate statements in the database that we have a response for
6. use semantic search instead of text similarity (full text search or fuzzywyzzy text matches)
    1. add embedding vectors (300D document vectors from spacy) to each statement and response in the db
    2. create a semantic index of the document vectors using `annoy` so "approximate nearest neighbors" (semantic matches) can be found quickly
    3. load the annoy index of the document vectors every time the server is started and use it to find the best reply in the database.
    4. use universal sentence encodings instead of docvecs from spacy.
7. create a UX for dialog graph creation/design:
    1. install [mxgraph](https://github.com/totalgood/mxgraph) in the django app
    2. create a basic page based on this mxgraph example so the user can build and save dialog to the db as a graph: [tutorial](https://jgraph.github.io/mxgraph/docs/tutorial.html#1), [example app](https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html)
    3. convert the dialog graph into a set of records/rows in the qary db so it acts
8. tag different dialog graphs in the db so the user can turn them on/off for their bot
    1. allow the user to prioritize some dialogs/models over others
    2. allow the user to create their own weighting function to prioritize individual statements produced by the api
9. train a character-based generative model
    1. decoder half of autoencoder to generate text based on docvecs from spacy
    2. decoder part of autoencoder to generate text based on universal sentence encodings
    3. train model to generate reply embeddings (doc vecs and/or use vecs) using statement embeddings (dialog engine encoder-decoder using docvecs or use vecs for the encoder half
10. add a therapy/mindfulness-coach feature to respond with mindfulness ideas to some queries/statements
11. add the "translate 'this text' to spanish" feature
    1. train character-based LSTM models on english-spanish, english-french, english-german, english<->whatever
    2. add module for this to the django app/api
12. AIML engine fallback
</p>

<h1>Inspiration</h1>
<p>
A lot of the patterns and ideas were gleaned from other awesome prosocial chatbots and modular open source frameworks.

### Mental Health Coaches

- [WYSA](wysa.io) from London is free
    - https://www.techinasia.com/ai-chatbot-wysa-touchkin-penguin
    - open source (touchkin)?
    - ionic?
    - passive sensing of sleep patterns (accelerometers?)
    - guided meditation
    - exercise suggestions
    - free text dialog with buttons to suggest replies
    - based on open source touchkin/mindlogger ?
    - [list of alternative apps](https://github.com/akeshavan/mHealthLandscape/blob/0ea138267f13af1c8a0733296ebcfb9683485528/mHealth_iOS.csv)
- [Replika](replika.ai) from US is paywalled
    - personality profile test
    - pay to unlock "skills" training
- [Youper](youper.ai) (thank you Maria and [tangibleai.com](tangibleai.com))
</p>

<h1>Open Source Frameworks</h1>
<p>
- [will](https://github.com/skoczen/will)
    - lang: python
    - web: zeromq
    - db: redis, couchbase, flat file, user-defined
    - integrations: hipchat, rocketchat, shell, slack
- [ai-chatbot-framework](https://github.com/alfredfrancis/ai-chatbot-framework/blob/master/app/intents/models.py)
    - lang: python
    - web: flask
    - orm: flask?
    - db: mongodb
    - nice general json syntax for specifying intent/goals for conversation manager (agent)
- [rasa](https://github.com/RasaHQ/rasa)
    - lang: python
    - web: sanic (async)
    - orm: sqlalchemy
    - db: sqlite
    - rich, complex, mature framework
- [botpress](https://github.com/botpress/botpress)
    - javascript (typescript)
    - meta-framework allowing your to write your own modules in javascript
- [Program-Y](https://github.com/keiffster/program-y/wiki)
    - python
    - web: flask (rest), sanic (async)
    - db: aiml flat files (XML)
    - integrations: facebook messenger, google search, kik, line, alexa, webchat, viber
</p>


{%endblock%}

qarysite/templates/question.html
{% extends 'home.html'%}
{% block body_block%}

<div class='jumbotron'>

    <form action = "" method = "get"> 
    <h3><label >Ask the bot a question: </label> </h3>
    <input type="text" name="n"> 
    <input type="submit" value="submit" > 
    <p><a href="{% url 'answer'%}">click for answer</a></p>
    </form>
</div>

{% endblock %}

qarysite/templates/team.html
{% extends 'home.html'%}
{% block body_block%}

<div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x100]" style="height: 50%; width: 100%; display: block;" src="../static/images/hobson.jpg" data-holder-rendered="true">
                <div class="card-body">
                  <p class="card-text">I develop conversational AI that assists instead of manipulates. We're building machine intelligence that can be directly controlled by humans, instead of the other way around. Volunteers and I are building a conversational AI for education at UCSD.edu, Springboard.com, TangibleAI.com, and NLPIA.org. Everything I do is open source, open data, open science. 

I pride myself in authentic, open communication. I share what I learn with those around me. </p>
                  <div class="d-flex justify-content-between align-items-center">  
                  </div>
                </div>
              </div>
            </div>



 <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="../static/images/maria.jpg" data-holder-rendered="true" style="height: 50%; width: 100%; display: block;">
                <div class="card-body">
                  <p class="card-text">A multi-disciplinary technologist and Forbes 30 under 30 social entrepreneur, passionate about solving problems and improve people's lives using digital technology and artificial intelligence. Currently redistributing the future with Tangible AI. </p>
                  <div class="d-flex justify-content-between align-items-center">
          
                  </div>
                </div>
              </div>
            </div>


            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="../static/images/mohammed.jpg" data-holder-rendered="true" style="height: 50%; width: 100%; display: block;">
                <div class="card-body">
                  <p class="card-text">I’m a Data Analyst professional with an IT engineer, focused on Computer Engineering working to better understand how machine learning activity helps and shapes business and health sectors. </p>
                  <div class="d-flex justify-content-between align-items-center">
          
                  </div>
                </div>
              </div>
            </div>


         

 <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="../static/images/travis.jpg" data-holder-rendered="true" style="height: 50%; width: 100%; display: block;">
                <div class="card-body">
                  <p class="card-text">With a professional background in software engineering, continual fascination in the fields of computer vision and natural language processing drove me to pursue the study of machine learning and data science beyond the late-night programming sessions and free weekends as a hobbyist. I deploy state-of-the-art predictive models for problems that prove to be too complex to solve with traditional means. </p>
                  <div class="d-flex justify-content-between align-items-center">
          
                  </div>
                </div>
              </div>
            </div>

<div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" src="../static/images/olesya.jpg" data-holder-rendered="true" style="height: 50%; width: 100%; display: block;">
                <div class="card-body">
                  <p class="card-text">Researcher with 10+ years experience in the areas of photonics and semiconductors, and almost 6 years of product development experience for early stage startup companies. Expert in R&D project management and new product prototyping. Experienced in statistical analysis, predictive modeling, data mining, data management, and visualization. Collaborated in multidisciplinary teams of scientists and engineers; initiated and led R&D projects; established new connections with the outside groups. </p>
                  <div class="d-flex justify-content-between align-items-center">
          
                  </div>
                </div>
              </div>
            </div>


{% endblock %}

  


 