qarysite/qary_app/urls.py
# from django.contrib import admin
# from django.urls import path
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns


from qary_app import views


app_name = 'qary_app'


urlpatterns = [


    url(r'answer/', views.reply, name='answer'),
    url(r'^(?P<pk>[-\w]+)/$', views.home_view, name='question'),
    # Rest_framework
    url('basic/', views.API_objects.as_view()),
    url('basic/<int:pk>/', views.API_objects_details.as_view()),




]
urlpatterns = format_suffix_patterns(urlpatterns)

qarysite/qary_post/urls.py
from django.conf.urls import url
from qary_post import views

app_name = 'qary_post'


urlpatterns = [

    url(r'^$', views.PostListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^new/$', views.PostCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.PostUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.PostDeleteView.as_view(), name='delete'),
]

qarysite/qarysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from qary_app import views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home_view),
    url(r'question/', views.home_view, name='question'),
    url(r'answer/', views.reply, name='answer'),
    url(r'^team/$', views.team, name='team'),
    url(r'^nlpia/$', views.nlpia, name='nlpia'),
    url(r'^post/', include('qary_post.urls')),
    url('register/', user_views.register, name='register'),
    url('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url('profile/', user_views.profile, name='profile'),
    url('basic/<int:pk>/', views.API_objects_details.as_view(), name='basic')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


#

qarysite/qary_post/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.


class Post(models.Model):
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qary_post:detail', kwargs={'pk': self.pk})

qarysite/qary_post/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from . import models
from django.urls import reverse_lazy


# Create your views here.


class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post
    template_name = 'qary_post/post_list,html'
    ordering = ['-create_date']
    paginated_by = 2


class PostDetailView(DetailView):
    context_object_name = 'post_detail'
    model = models.Post
    template_name = 'qary_post/post_detail.html'


class PostCreateView(CreateView):

    fields = ('author', 'title', 'text')
    model = models.Post


class PostUpdateView(UpdateView):

    fields = ('title', 'text')
    model = models.Post


class PostDeleteView(DeleteView):

    model = models.Post
    success_url = reverse_lazy('qary_post:list')

qarysite/qary_post/templates/qary_post/post_confirm_delete.html
{% extends 'home.html'%}
{% block body_block%}


<h1>Delete {{posts.name}}?</h1>

<form method="POST">
	{%csrf_token%}
	<input type="submit" value="delete" class='btn btn-danger'>
	<a href="{%url 'qary_post:list'%}">Cancel</a>
</form>

{% endblock %}

qarysite/qary_post/templates/qary_post/post_detail.html
{% extends 'home.html'%}
{% block body_block%}

    <center>
      <div class="col-md-6" >
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start" contenteditable="true" spellcheckker="false" >
              <strong class="d-inline-block mb-2 text-success">{{post_detail.title}}</strong>
              <h3 class="mb-0">
                <p>{{post_detail.author}}</p>
              </h3>
              <p class="card-text mb-auto">{{post_detail.text}}</p>
              
            </div>
          </div>
    </div>


            <!-- Update button -->
         
              <p><a class='btn btn-warning'href="{% url 'qary_post:update' pk=post_detail.pk %}">Update</a></p>
           
              <!--Delete button-->              
                
                <p><a class='btn btn-danger'href="{% url 'qary_post:delete' pk=post_detail.pk %}">Delete</a></p> 
              


</center>



{% endblock %}

qarysite/qary_post/templates/qary_post/post_form.html
{% extends 'home.html'%}
{% block body_block%}

<h1>
	{%if not form.instance.pk %}
	
	Create Post
	
	{%else%}
	
	Update Post
	
	{%endif%}
</h1>
<form method='POST'>
	{%csrf_token%} 
	{{form.as_p}}
	<input type="submit" value="submit" class='btn btn-primary'>
</form>


{% endblock %}

qarysite/qary_post/templates/qary_post/post_list.html
{% extends 'home.html'%}
{% block body_block%}


{% for p in posts %}
 <center>
      <div class="col-md-6" >

      	
      	
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start"  spellcheckker="false" style='text-align: justify;' >
              <a href="{{p.id}}" class="d-inline-block mb-4 text-success">{{p.title}}</a>
              {{p.create_date}}
              <h3 class="mb-0">


              	 <img class="rounded-circle account-img mb-2" src="{{user.profile.image.url}}">

                <p>{{p.author}}</p>
              </h3>
              <p class="card-text mb-auto">{{p.text|safe}}</p>
              
            </div>
          </div>
    </div>
{%endfor%}

{% endblock %}